/**
 * Catalogue of all distraction events for the Finger Challenge.
 * Includes integration with existing jump scare library.
 */

import type { DistractionEvent, JumpScareEvent, DistractionIntensity } from './types';

/**
 * Existing jump scare assets integrated into the new system.
 * These are high-intensity, rare events that use the existing library.
 */
export const jumpScareEvents: JumpScareEvent[] = [
  {
    id: 'jumpscare-01',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-01.jpg',
    assetLandscape: '/assets/scares/scare-01-wide.jpg',
    audio: '/assets/screams/scream-1.mp3',
    resultMessages: {
      early: ['THE FACE GOT YOU.', 'JUMPED TOO SOON.'],
      survived: ['YOU SURVIVED THE SCARE.', 'NERVES OF STEEL.'],
    },
  },
  {
    id: 'jumpscare-02',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-02.jpg',
    assetLandscape: '/assets/scares/scare-02-wide.jpg',
    audio: '/assets/screams/scream-2.mp3',
  },
  {
    id: 'jumpscare-03',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-03.jpg',
    assetLandscape: '/assets/scares/scare-03-wide.jpg',
    audio: '/assets/screams/scream-3.mp3',
  },
  {
    id: 'jumpscare-04',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-04.jpg',
    assetLandscape: '/assets/scares/scare-04-wide.jpg',
    audio: '/assets/screams/scream-4.mp3',
  },
  {
    id: 'jumpscare-05',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-05.jpg',
    assetLandscape: '/assets/scares/scare-05-wide.jpg',
    audio: '/assets/screams/scream-5.mp3',
  },
  {
    id: 'jumpscare-06',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-06.jpg',
    assetLandscape: '/assets/scares/scare-06-wide.jpg',
    audio: '/assets/screams/scream-1.mp3',
  },
  {
    id: 'jumpscare-07',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-07.jpg',
    assetLandscape: '/assets/scares/scare-07-wide.jpg',
    audio: '/assets/screams/scream-2.mp3',
  },
  {
    id: 'jumpscare-08',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-08.jpg',
    assetLandscape: '/assets/scares/scare-08-wide.jpg',
    audio: '/assets/screams/scream-3.mp3',
  },
  {
    id: 'jumpscare-09',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-09.jpg',
    assetLandscape: '/assets/scares/scare-09-wide.jpg',
    audio: '/assets/screams/scream-4.mp3',
  },
  {
    id: 'jumpscare-11',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-11.jpg',
    assetLandscape: '/assets/scares/scare-11-wide.jpg',
    audio: '/assets/screams/scream-5.mp3',
  },
  {
    id: 'jumpscare-12',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-12.jpg',
    assetLandscape: '/assets/scares/scare-12-wide.jpg',
    audio: '/assets/screams/scream-1.mp3',
  },
  {
    id: 'jumpscare-13',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-13.jpg',
    assetLandscape: '/assets/scares/scare-13-wide.jpg',
    audio: '/assets/screams/scream-2.mp3',
  },
  {
    id: 'jumpscare-14',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-14.jpg',
    assetLandscape: '/assets/scares/scare-14-wide.jpg',
    audio: '/assets/screams/scream-3.mp3',
  },
];

/**
 * Standard distraction events - massive variety, longer durations.
 */
export const distractionEvents: DistractionEvent[] = [
  // Random numbers - most important
  {
    id: 'random-numbers',
    minTargetSeconds: 10,
    earliestProgress: 0.1,
    latestProgress: 0.9,
    durationMs: 5000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 10,
  },
  
  // Thumb jokes (high weight since 99% use thumbs)
  {
    id: 'thumb-joke-1',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  {
    id: 'thumb-joke-2',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  {
    id: 'thumb-joke-3',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  {
    id: 'thumb-joke-4',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 3500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'thumb-joke-5',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  
  // Counting taunts
  {
    id: 'counting-taunt-1',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 4500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 7,
  },
  {
    id: 'counting-taunt-2',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 4500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 7,
  },
  {
    id: 'counting-taunt-3',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 3500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  {
    id: 'counting-taunt-4',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 4500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 7,
  },
  
  // General taunts (20 variations)
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `taunt-${i + 1}`,
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 1 as DistractionIntensity,
    safeForReducedMotion: true,
    weight: 5,
  })),
  
  // Fake time
  {
    id: 'wrong-time',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 6,
  },
  
  // Urgent messages
  {
    id: 'release-now',
    minTargetSeconds: 10,
    earliestProgress: 0.4,
    latestProgress: 0.85,
    durationMs: 3500,
    intensity: 3,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'almost-there',
    minTargetSeconds: 10,
    earliestProgress: 0.5,
    latestProgress: 0.9,
    durationMs: 3500,
    intensity: 2,
    incompatibleWith: ['fake-finish'],
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'fake-finish',
    minTargetSeconds: 20,
    earliestProgress: 0.6,
    latestProgress: 0.9,
    durationMs: 3000,
    intensity: 3,
    incompatibleWith: ['almost-there'],
    safeForReducedMotion: true,
    weight: 2,
  },
  
  // Notifications
  {
    id: 'fake-battery',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'fake-message',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 4500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 5,
  },
  
  // Animated elements
  {
    id: 'pigeon',
    minTargetSeconds: 10,
    earliestProgress: 0.15,
    latestProgress: 0.75,
    durationMs: 6000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'tiny-horse',
    minTargetSeconds: 10,
    earliestProgress: 0.15,
    latestProgress: 0.8,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'wrong-countdown',
    minTargetSeconds: 10,
    earliestProgress: 0.4,
    latestProgress: 0.85,
    durationMs: 4500,
    intensity: 2,
    incompatibleWith: ['fake-finish'],
    safeForReducedMotion: true,
    weight: 4,
  },
];

export const allDistractionEvents = [...distractionEvents, ...jumpScareEvents];
