/**
 * Catalogue of all distraction events for the Finger Challenge.
 * Includes integration with existing jump scare library.
 */

import type { DistractionEvent, JumpScareEvent } from './types';

/**
 * Existing jump scare assets integrated into the new system.
 * These are high-intensity, rare events that use the existing library.
 */
export const jumpScareEvents: JumpScareEvent[] = [
  {
    id: 'jumpscare-01',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-01.jpg',
    assetLandscape: '/assets/scares/scare-01-wide.jpg',
    audio: '/assets/screams/scream-1.mp3',
    resultMessages: {
      early: ['THE FACE GOT YOU.', 'JUMPED TOO SOON.'],
      survived: ['YOU SURVIVED THE SCARE.', 'NERVES OF STEEL.'],
    },
  },
  {
    id: 'jumpscare-02',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-02.jpg',
    assetLandscape: '/assets/scares/scare-02-wide.jpg',
    audio: '/assets/screams/scream-2.mp3',
  },
  {
    id: 'jumpscare-03',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-03.jpg',
    assetLandscape: '/assets/scares/scare-03-wide.jpg',
    audio: '/assets/screams/scream-3.mp3',
  },
  {
    id: 'jumpscare-04',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-04.jpg',
    assetLandscape: '/assets/scares/scare-04-wide.jpg',
    audio: '/assets/screams/scream-4.mp3',
  },
  {
    id: 'jumpscare-05',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-05.jpg',
    assetLandscape: '/assets/scares/scare-05-wide.jpg',
    audio: '/assets/screams/scream-5.mp3',
  },
  {
    id: 'jumpscare-06',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-06.jpg',
    assetLandscape: '/assets/scares/scare-06-wide.jpg',
    audio: '/assets/screams/scream-1.mp3',
  },
  {
    id: 'jumpscare-07',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-07.jpg',
    assetLandscape: '/assets/scares/scare-07-wide.jpg',
    audio: '/assets/screams/scream-2.mp3',
  },
  {
    id: 'jumpscare-08',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-08.jpg',
    assetLandscape: '/assets/scares/scare-08-wide.jpg',
    audio: '/assets/screams/scream-3.mp3',
  },
  {
    id: 'jumpscare-09',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-09.jpg',
    assetLandscape: '/assets/scares/scare-09-wide.jpg',
    audio: '/assets/screams/scream-4.mp3',
  },
  {
    id: 'jumpscare-11',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-11.jpg',
    assetLandscape: '/assets/scares/scare-11-wide.jpg',
    audio: '/assets/screams/scream-5.mp3',
  },
  {
    id: 'jumpscare-12',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-12.jpg',
    assetLandscape: '/assets/scares/scare-12-wide.jpg',
    audio: '/assets/screams/scream-1.mp3',
  },
  {
    id: 'jumpscare-13',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-13.jpg',
    assetLandscape: '/assets/scares/scare-13-wide.jpg',
    audio: '/assets/screams/scream-2.mp3',
  },
  {
    id: 'jumpscare-14',
    type: 'jumpscare',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.85,
    durationMs: 950,
    intensity: 3,
    cooldownMs: 5000,
    safeForReducedMotion: false,
    weight: 1,
    assetPortrait: '/assets/scares/scare-14.jpg',
    assetLandscape: '/assets/scares/scare-14-wide.jpg',
    audio: '/assets/screams/scream-3.mp3',
  },
];

/**
 * Standard distraction events.
 */
export const distractionEvents: DistractionEvent[] = [
  {
    id: 'fake-battery',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 2000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'pigeon',
    minTargetSeconds: 10,
    earliestProgress: 0.15,
    latestProgress: 0.75,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'screen-shake',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 1500,
    intensity: 2,
    safeForReducedMotion: false,
    weight: 4,
  },
  {
    id: 'wrong-countdown',
    minTargetSeconds: 10,
    earliestProgress: 0.4,
    latestProgress: 0.85,
    durationMs: 3000,
    intensity: 2,
    incompatibleWith: ['fake-celebration'],
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'motivational-coach',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 2500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'finger-inspection',
    minTargetSeconds: 10,
    earliestProgress: 0.25,
    latestProgress: 0.65,
    durationMs: 3000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'fake-achievement',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.7,
    durationMs: 2000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'emergency-question',
    minTargetSeconds: 20,
    earliestProgress: 0.3,
    latestProgress: 0.75,
    durationMs: 3500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'mosquito',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.8,
    durationMs: 3000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'spider',
    minTargetSeconds: 10,
    earliestProgress: 0.25,
    latestProgress: 0.75,
    durationMs: 4000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'fake-crack',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 2500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'bouncing-emoji',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.75,
    durationMs: 3000,
    intensity: 1,
    safeForReducedMotion: false,
    weight: 4,
  },
  {
    id: 'upside-down',
    minTargetSeconds: 20,
    earliestProgress: 0.3,
    latestProgress: 0.7,
    durationMs: 3500,
    intensity: 2,
    safeForReducedMotion: false,
    weight: 3,
  },
  {
    id: 'fake-loading',
    minTargetSeconds: 10,
    earliestProgress: 0.25,
    latestProgress: 0.75,
    durationMs: 3000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'unhelpful-advice',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 3500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'suspicious-button',
    minTargetSeconds: 20,
    earliestProgress: 0.3,
    latestProgress: 0.75,
    durationMs: 2500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'tiny-horse',
    minTargetSeconds: 10,
    earliestProgress: 0.15,
    latestProgress: 0.8,
    durationMs: 2500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'weather',
    minTargetSeconds: 20,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 4000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'screen-shrink',
    minTargetSeconds: 20,
    earliestProgress: 0.3,
    latestProgress: 0.75,
    durationMs: 2500,
    intensity: 2,
    safeForReducedMotion: false,
    weight: 3,
  },
  {
    id: 'fake-celebration',
    minTargetSeconds: 20,
    earliestProgress: 0.5,
    latestProgress: 0.9,
    durationMs: 3000,
    intensity: 2,
    incompatibleWith: ['wrong-countdown'],
    safeForReducedMotion: false,
    weight: 3,
  },
  {
    id: 'day-night-cycle',
    minTargetSeconds: 20,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 5000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'fake-timer',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 1500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'anticipation-buildup',
    minTargetSeconds: 20,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 3000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'false-safety',
    minTargetSeconds: 20,
    earliestProgress: 0.1,
    latestProgress: 0.5,
    durationMs: 2000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 2,
  },
  {
    id: 'youre-counting',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.7,
    durationMs: 2500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  {
    id: 'stop-counting',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 2000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 6,
  },
  {
    id: 'almost-there',
    minTargetSeconds: 10,
    earliestProgress: 0.4,
    latestProgress: 0.7,
    durationMs: 1500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'way-too-early',
    minTargetSeconds: 10,
    earliestProgress: 0.15,
    latestProgress: 0.4,
    durationMs: 1500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'finger-getting-tired',
    minTargetSeconds: 20,
    earliestProgress: 0.5,
    latestProgress: 0.85,
    durationMs: 2000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'overthinking',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.7,
    durationMs: 2500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'friend-did-better',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.6,
    durationMs: 3000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'fake-vibration',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 800,
    intensity: 2,
    safeForReducedMotion: false,
    weight: 4,
  },
  {
    id: 'probably-wrong',
    minTargetSeconds: 10,
    earliestProgress: 0.4,
    latestProgress: 0.8,
    durationMs: 2000,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'time-paradox',
    minTargetSeconds: 20,
    earliestProgress: 0.3,
    latestProgress: 0.7,
    durationMs: 3000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'swipe-notification',
    minTargetSeconds: 10,
    earliestProgress: 0.2,
    latestProgress: 0.75,
    durationMs: 2500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'math-problem',
    minTargetSeconds: 10,
    earliestProgress: 0.25,
    latestProgress: 0.7,
    durationMs: 3500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'distracted-yet',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.7,
    durationMs: 1800,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 5,
  },
  {
    id: 'release-now',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.75,
    durationMs: 1200,
    intensity: 3,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'seconds-feel-longer',
    minTargetSeconds: 20,
    earliestProgress: 0.4,
    latestProgress: 0.8,
    durationMs: 2500,
    intensity: 1,
    safeForReducedMotion: true,
    weight: 4,
  },
  {
    id: 'already-failed',
    minTargetSeconds: 10,
    earliestProgress: 0.5,
    latestProgress: 0.85,
    durationMs: 2000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'screen-dim',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.8,
    durationMs: 2500,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'fake-finish',
    minTargetSeconds: 20,
    earliestProgress: 0.6,
    latestProgress: 0.9,
    durationMs: 2000,
    intensity: 3,
    incompatibleWith: ['fake-celebration', 'almost-there'],
    safeForReducedMotion: true,
    weight: 3,
  },
  {
    id: 'zoom-in',
    minTargetSeconds: 10,
    earliestProgress: 0.3,
    latestProgress: 0.7,
    durationMs: 2000,
    intensity: 2,
    safeForReducedMotion: false,
    weight: 3,
  },
  {
    id: 'notification-spam',
    minTargetSeconds: 20,
    earliestProgress: 0.3,
    latestProgress: 0.75,
    durationMs: 4000,
    intensity: 2,
    safeForReducedMotion: true,
    weight: 3,
  },
];

export const allDistractionEvents = [...distractionEvents, ...jumpScareEvents];
